-- 1) LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL
USE EMPLOYEE;
SELECT ENAME 
FROM EMP
WHERE COMM IS null;
-- 2) LIST ALL THE EMPLOYEES WHO DON'T HAVE A REPORTING MANAGER
SELECT ENAME 
FROM EMP
WHERE ENAME NOT IN ('MANAGER');
-- 3) LIST ALL THE SALESMEN IN DEPT 30
SELECT JOB
FROM EMP
WHERE DEPTNO IN (30);
-- 4 LIST ALL THE SALESMEN iN dePt nUMBER 30 AND HAVING SALARY
-- GREATER THAN 1500
SELECT * 
FROM EMP
WHERE JOB IN ('SALESMAN') AND DEPTNO IN (30) AND SAL > 1500;
-- 5) LIST ALL THE EMPLoYEeS WHoSe NAME STARTS WITH 's' OR 'A'
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'S%' OR ENAME LIKE 'A%';
-- 6) LIST ALL THE. EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT
-- 10 & 20.
SELECT ENAME
FROM EMP
WHERE DEPTNO IN(10,30);
-- 7 LIST THE EMPLOYEES WHOSE NAME DOES NOT START WITH 'S'
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'S%';
-- 8) LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS
-- IN DEPT 10
SELECT ENAME 
FROM EMP
WHERE ENAME  IN ('MANAGER') AND DEPTNO IN (10);
-- 9) LIST aLl THe EMPLoYEeS WHOSE COMMISSION IS NULL AND
-- WORKING AS CLERK
SELECT ENAME
FROM EMP
WHERE COMM IS NULL AND JOB = 'CLERK';
-- 10) LIST ALL THE EMPL OYEeS WHO DON'T HAVE A REPORTING MANAGER
-- IN DEPTNO 10 OR 30
SELECT ENAME 
FROM EMP
WHERE JOB NOT IN ('MANAGER') AND DEPTNO IN (10,30); 
-- 11) LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450
SELECT ENAME 
FROM EMP
WHERE DEPTNO IN (30) AND SAL > 2450;
-- 12) LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY
-- GREATER THAN 2500
SELECT ENAME
FROM EMP
WHERE DEPTNO IN (20) AND SAL > 2500;
-- +13) LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH 'M' OR J
SELECT ENAME 
FROM EMP
WHERE ENAME LIKE 'M%' OR 'J%';
-- 14) LIST ALL THE EMPLOYEES WITH ANNUAL SALARY
-- EXCEPT THOSE WHO ARE WORKING IN DEPT 30
SELECT ENAME , SAL*12 AS ANNUAL_SALARY
FROM EMP
WHERE DEPTNO IN (30);
-- 15) LIST THE EMPLOYeeS WhoSe NAME dOES NOT END WITH ES'OR R
SELECT ENAME
FROM EMP
WHERE ENAME NOT LIKE '%ES' AND ENAME NOT LIKE '%R';
-- 16) LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS
-- IN DEPT 10 ALONG WITh 10% HIKE IN ANNUAL SALARY
SELECT ENAME, SAL*12+SAL*12/10 AS "10% HIKE IN ANNUAL_SALARY"
FROM EMP
WHERE JOB IN ('MANAGER') AND DEPTNO IN (10);
-- 17 DISPLAY ALL The EMPLoYEE WHO ARE SALESMAN and HAVING *E' AS
-- THE 2ND LAST CHARACTER IN ENAME BUT SALARY HAVING EXACTLY
-- 4 CHARACTER
SELECT ENAME 
FROM EMP
WHERE JOB IN ('SALESMAN') AND ENAME LIKE '_E%' AND SAL LIKE'____';
-- 18) DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81
-- 19) DISPLAY ALL ThE eMPLoyee who ArE JOINED IN FEB
-- 20) LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND
-- CLERKS IN DEPT 10 AND 20 WiTH A SALARY IN THE RANGE OF 1000 TO
-- 3000.