-- ASSIGNMENT QUESTIONS ON GROUP BY


-- 1.WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT
-- EXCEPT PRESIDENT

use employee;
select count(*),DEPTNO
FROM EMP
WHERE JOB NOT IN ('PRESIDENT')
GROUP BY DEPTNO;
-- 2.WAQTD TOTAL SaLary needed to PaY aLl THE EMPLOYEES IN EACH
-- JOB.
SELECT SUM(SAL),JOB
FROM EMP
GROUP BY JOB;
-- 3. WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH
-- DEPARTMENT
SELECT COUNT(*),DEPTNO
FROM EMP
WHERE JOB IN ('MANAGER')
GROUP BY DEPTNO;
-- 4.W aOTd aVG SaLary needed to pay aLll the EMPLOYEES IN EACH
-- DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20.
SELECT AVG(SAL),DEPTNO
FROM EMP
WHERE DEPTNO NOT IN (20)
GROUP BY DEPTNO;
-- 5.WAQTD NUMBER OF EMPLOYEES HA VING CHARACTER 'A' IN THEIR NAMES
-- IN EACH JOB
SELECT COUNT(*),JOB
FROM EMP
WHERE ENAME LIKE '%A%'
GROUP BY JOB;
-- 6.WaQTD NUMbER OF EMPLoEeS aNd avg SaLary needed TO PAY THE
-- EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT
SELECT COUNT(*),AVG(SAL),DEPTNO
FROM EMP
WHERE SAL > 2000
GROUP BY DEPTNO;
-- 7.WAQTD ToTAL SALaRy NEeded to PAy ANd NUMBER OF SALESMANS IN
-- EACH DEPT.
SELECT COUNT(*),SUM(SAL),DEPTNO
FROM EMP
WHERE JOB = 'SALESMAN'
GROUP BY DEPTNO;
-- 8.WAQTD NUMBER OF EMPLOYEES AND MAXIMUM SALARIES IN EACH JOB
SELECT COUNT(*),MAX(SAL),JOB
FROM EMP
GROUP BY JOB;
-- 9.WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH
-- DEPT.
SELECT MAX(SAL),DEPTNO
FROM EMP
GROUP BY DEPTNO;
-- 10.W AOTD NUMBER OF TiMES THE SALARIES PRESENT IN EMPLOYEE TABLE.
SELECT COUNT(SAL)
FROM EMP;


-- ASSIGNMENT QUESTIONS ON HAVING CLAUSE
-- 1.WAQTD DNO AND NUMBER OF clerks WORKING IN EACH DEPT fF THERE ARE
-- ATLEAST 2 CLERKS IN EACH DEPT
SELECT COUNT(*),DEPTNO
FROM EMP
WHERE JOB = 'CLERK'
GROUP BY DEPTNO
HAVING COUNT(*) >= 2;
-- - 2.WAQTD DNO AND TOTAL SALaRy nEedEd tO PAY ALL EMP IN EACH DEPT
-- IF THERE ARE ATLEAST 4 EMP IN EACH DEPT
SELECT COUNT(*),SUM(SAL),DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) >=4;
-- 3.WAQTD NUMBER OF EMPS AND SUM OF SALARY PAID IN EACH JOB ONLY
-- iF THE TOTAL SAL NEedED TO PAY_EXCEEDS 3800
SELECT COUNT(*),SUM(SAL),JOB
FROM EMP
GROUP BY JOB
HAVING SUM(SAL) > 3800;
-- 4.WAQTD DEPTNO AND NUMBER OF MANAGERS WORKING IN EACH DEPT
-- ONLY IF THERE ARE ATLEAST 2 EMP WORKING AS MANAGER
SELECT COUNT(*), DEPTNO
FROM EMP
WHERE JOB = 'MANAGER'
GROUP BY DEPTNO
HAVING COUNT(*) >= 2;
-- 5.WAQTD JOB AND MAX SAL OF EMP INIEACH JOB IF THE MAX SAL EXCEEDS
-- 2600
SELECT MAX(SAL),JOB
FROM EMP
WHERE SAL > 2600
GROUP BY JOB;
-- 6.WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE
SELECT COUNT(*),SAL
FROM EMP
GROUP BY SAL;
-- 7.WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE
SELECT HIREDATE
FROM EMP
GROUP BY HIREDATE
HAVING COUNT(*) > 1;
-- 8.WAQTD AVG SALARy OF EaCH DEPT iF AVG SAL IS LESS THAN 3000
SELECT AVG(SAL),DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) < 3000;