-- NOT LIKE:
--      IT IS OPPOSITE TO THE KEYWORD LIKE. INSTEAD OF SELECTING IT WILL REJUCT THE MATCHING PATTERN

-- SYNTEX:
--     COL_NAME/EXP NOT LIKE 'MATCHING_PATTERN';

-- WAQTD NAMES OF EMPLOYEES WHICH DOES NOT START WITH A
USE EMPLOYEE;
SELECT *
FROM emp
WHERE ENAME NOT LIKE 'A%';

-- WAQTD NAMES OF THE EMPLOYEES WHO ARE EARNING THREE DIGIT SALARY
SELECT *
FROM EMP
WHERE ENAME NOT LIKE '___';

-- WAQTD NAMES OF THE EMPLOYEES WHO NAME IS STARTING WITH A AND ENDS WITH S
SELECT *
FROM emp
WHERE ENAME NOT LIKE '%A' OR ENAME NOT LIKE 'S%';





-- ESCAPE:
--         This keyword is used when we are searching for wildcard characters in the pattern.
        
        
        
-- WAQTD NAMES OF EMPLOYEES HAVING % SIGN
    SELECT ENAME 
    FROM EMP
    WHERE ENAME LIKE '%@%%' ESCAPE '@';