-- IS OPERATOR:
--    IT IS USED TO COMPARE ONLY THE NULL VALUES
--    
--    SYNTEX:
--    COL_NAME/EXP IS NULL
--    
--    WAQTD DETAILS OF EMPLOYEES WHO ARE NOT GETTING ANY COMESSION

USE EMPLOYEE;
SELECT *
FROM EMP
WHERE COMM IS NULL;

-- WAQTD DETAILS OF EMPLOYEES WHO ARE HAVING MGR NUMBERS
SELECT *
FROM EMP
WHERE MGR IS NULL;