-- NOT IN:
--     It is opposite to in operator. instead of selecting the values it will reject the values

-- syntex:
-- col_name / exp NOT IN(VAL1,VAL2,VAL3...)

-- WAQTD DETAILS OF EMPLOYEES EXCEPT MANAGER AND CLERK
USE EMPLOYEE;
SELECT *
FROM EMP
WHERE JOB NOT IN('MANAGER','CLERK');

-- WAQTD DETAILS OF EMPLOYEES EXCEPT MANAGER AND CLERK IN DEPT 10

SELECT *
FROM EMP
WHERE JOB NOT IN('MANAGER','CLERK') AND DEPTNO IN(10);

-- WAQTD DETAILS OF EMPLOYEES EXCEPT IN DEPT 10,40
SELECT *
FROM EMP
WHERE DEPTNO NOT IN(10,40);

