-- WAQTD NUMBER OF TYPES OF EACH SALARY IS PRESENT IN EMP TABLE
USE EMPLOYEE;
SELECT COUNT(*),SAL
FROM EMP
GROUP BY SAL;

-- WAQTD NUMBER OF TYPES OF EACH SALARY IS REPEATED IN EMP TABLE
SELECT COUNT(*) -1,SAL
FROM EMP
GROUP BY SAL;

-- HAVING CLAUSE:
-- * HAVING CLAUSE IS USED TO FILTER THE GROUPS
-- * HAVING CLAUSE ALWAYS EXISTS AFTER THE GROUP CLAUSE

-- SYNTEX:
--   SELECT GROUPBY_FUNCTION/GROUPBY_EXP
--   FROM TAB_NAME
--   [WHERE <FILTER_CONDITIONS>]
--   GROUP BY COL_NAME/EXP
--   HAVING <GROUP FILTER CONDITION>

-- WAQTD MAX SAL, MIN SAL, AVG SAL OF EMPLOYEES IN EACH DEPT IF MIN SAL AND AVG SAL ARE MORE THAN 1000

SELECT MAX(SAL),MIN(SAL),AVG(SAL),DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) > 1000 AND MIN(SAL) > 1000;

-- WAQTD NUMBER OF EMPLOYEES IN EACH DEPT IF ALMOST 4 EMPLOYEES ARE WORKING IN THE DEPT
SELECT COUNT(*),DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) < 4;

-- WAQTD NO.OF EMPLOYEES IN EACH DEPT HAVING 'A' IN THEIR NAME IN EACH DEPT IF ATLEAST
-- 2 EMPLOYEES HAVING A IN THEIR NAME.
SELECT COUNT(*),DEPTNO
FROM EMP
WHERE ENAME LIKE '%A%'
GROUP BY DEPTNO
HAVING COUNT(*) >= 2;



