-- LIKE:
--   IT IS USED TO MATCH THE PATTERNS
--   
--   SYNTEX:
--     COL_NAME/EXP LIKE 'PATTERN_TO_MATCH'
--     
--     IN THE PATTERN MATCHING PROCESS WE USE TWO WHITE CARD CHARACTERS(%,_)
--     
--              |-------------->ACCEPT ANY NO OF CHARACTERS  
--              |
--     %--------|---------------> ACCEPT SAME CHARACTER ANY NO OF TIMES
--              |
--              |---------------> ACCEPT NO CHARACTERS
--              
--              
-- _  -----------> ACCEPT ONLY ONE CHARACTER. IT MAYBE ANY CHARACTER

-- WAQTD NAMES OF THE EMPLOYEES STARING WITH D
USE EMPLOYEE;
SELECT *
FROM EMP
WHERE ENAME LIKE 'D%';

-- WAQTD NAMES OF THE EMPLOYEES STARING ENDING S
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

-- WAQTD NAMES OF THE EMPLOYEES WHO IS HAVING A
SELECT *
FROM emp
WHERE ENAME LIKE '%A%';

-- WAQTD NAMES OF THE EMPLOYEES WHO IS HAVING CONSICUTIVE LL
SELECT *
FROM emp
WHERE ENAME LIKE '%LL%';


