-- GROUP BY:-
-- ----------------------------------
-- GROUP BY CLAUSE IS USED TO GROUP THE RECORDS

-- syntex:
--   SELECT GROUP_FUNCTION/ GROUP_BY_EXPRESSION
--   FROM TAB_NAME
--   [WHERE <FILTERED_CONDITIONS>]
--   GROUP BY COL_NAME/ EXPRESSION;

-- WAQTD MAX AND MIN SAL PAID TO THE EMPLOYEE IN EACH JOB
SELECT MAX(SAL),MIN(SAL),JOB
FROM emp
GROUP BY JOB;

-- WAQTD NO OF EMPLOYEES HAVING A IN THEIR NAME
SELECT COUNT(*),DEPTNO
FROM emp
WHERE ENAME LIKE '%A%'
GROUP BY DEPTNO;

-- WAQTD TOTAL SALARY AND AVG SALARY PAID TO THE EMPLOYEES IN EACH DEPT IF
-- THERE ARE EARNING SALARY MORE THAN 1500
SELECT SUM(SAL),AVG(SAL),DEPTNO
FROM EMP
WHERE SAL > 1500
GROUP BY DEPTNO;

-- 1.WAQTD NUMBER OF EMPLOYEES GETTING SALARY LESS
-- THAN 2000 IN DEPTNO 10
SELECT COUNT(*),DEPTNO
FROM emp
WHERE SAL < 2000 AND DEPTNO = 10
GROUP BY DEPTNO;
-- 2.WaQTD TOTAL SALARY NEEDED TO PAY EMPLOYEES
-- WORKING AS CLERK
SELECT SUM(SAL),JOB
FROM EMP
WHERE JOB = 'CLERK'
GROUP BY JOB;
-- 3.WAQTD AVERaGE SALARY NEEDED TO PAY ALL
-- EMPLOYEES
SELECT AVG(SAL)
FROM emp
-- 4.WAQTD NUMBER OF EMPLOYEES HAVING 'A' AS THEIR
-- FIRST CHARACTER
SELECT COUNT(*), ENAME
FROM EMP
WHERE ENAME LIKE 'A%'
GROUP BY ENAME;
-- 5.WaQTD NUMBER OF EMPLOYEES WORKING AS CLERK OR
-- MANAGER
SELECT COUNT(*),JOB
FROM emp
WHERE JOB = 'CLERK' OR JOB = 'MANAGER'
GROUP BY JOB;
-- 6.WaQTD ToTAL SALaRy NEEDED TO PAY EMPLOYEES
-- HIRED IN FEB
SELECT DEPTNO, SUM(SAL) AS TOTAL_SALARY
FROM EMP
WHERE MONTH(HIREDATE) = 2
GROUP BY DEPTNO;
-- 7.WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839 (MGR)
SELECT COUNT(*),ENAME
FROM EMP
WHERE MGR IN (7839)
GROUP BY ENAME;
-- 8.WAQTD NUMBER OF EMPLOYEES GETTING COMISSION IN
-- DEPTNO 30
SELECT COUNT(*),ENAME
FROM EMP
WHERE COMM>0 AND DEPTNO = 30
GROUP BY ENAME;
-- 9.WAQTD AVG SAL , TOTAL SAL , NUMBER OF EMPS AND
-- MAXIMUM SALARY GIVEN TO EMPLOYEES WORKING AS
-- PERSIDENT
SELECT avg(SAL),SUM(SAL),COUNT(SAL),ENAME
FROM emp
WHERE JOB = 'PRESIDENT'
GROUP BY ENAME;
-- 10.W aOTd NUMbeR Of emPLOyeeS HAVING 'A' IN THEIR
-- NAMES
SELECT COUNT(*),ENAME
FROM emp
WHERE ENAME LIKE '%A%'
GROUP BY ENAME;
-- 11.WAQTD NUMBER OF EMPS AND TOTAL SALARY NEEDED
-- TO PAY the eMPLOyEES WHO HAVE 2 CONSICUTIVE L's IN
-- THEIR NAMES
SELECT COUNT(*) AS TOTAL_EMPS,
       SUM(SAL) AS TOTAL_SALARY
FROM EMP
WHERE ENAME LIKE '%LL%';
-- 12.WAOTD NUMBER OF DEPARTMENTS PRESENT IN
-- EMPLOYEE TABLE
SELECT COUNT(distinct DEPTNO )
FROM EMP;
-- 13.WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER "Z"
-- IN THEIR NAMES
SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMP
WHERE ENAME LIKE '%Z%';
-- 14.WaOTd NUMBER OF EMPLOYEES HAVING '$' IN THEIR
-- NAMES
SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMP
WHERE ENAME LIKE '%$%';
-- 15.WAQTD TOTAL SALARY GIVEN TO EMPLOYEES WORKING
-- AS CLERK IN DEPT 30
SELECT AVG(SAL),ENAME
FROM EMP
WHERE JOB IN('CLERK') AND DEPTNO = 30
GROUP BY ENAME;
-- 16.W AQTd MAXiMUM SALaRY GivEN TO THE EMPLOYEES
-- WORKING AS ANALYST
SELECT AVG(SAL),ENAME
FROM EMP
WHERE JOB IN('ANALYST') 
GROUP BY ENAME;
-- 17.WAQTD NUMBER OF DISTINCT SALARIES PRESENT IN
-- EMPLOYEE TABLE
SELECT COUNT(distinct SAL)
FROM emp;
-- 18.WaQTD NUMBER OF JOBS PRESENT IN EMPLOYEE TABLE
SELECT COUNT(distinct JOB)
FROM EMP;
-- 19.WATQD AVG SALARY GIVEN TO THE CLERK
SELECT avg(SAL),ENAME
FROM EMP
WHERE JOB = 'CLERK'
GROUP BY ENAME;
-- 20. WAOTD MINIMUM SALARY GIVEN TO THE EMPLOYEES
-- WHO WORK IN DEPT 10 AS MANAGER OR A CLERK
SELECT MIN(SAL),ENAME
FROM emp
WHERE JOB = 'CLERK' AND DEPTNO = 10
group by ENAME;