-- BETWEEN:
--     IT IS USED TO COMPARE THE RANGE OF THE VALUES
--     
--     SYNTEX:
--           COL_NAME/EXP BETWEEN(LOW_RANGE AND HIGH_RANGE)

-- WAQTD DETAILS OF EMPLOYEES WHO ARE EARNING SALARY IN THE RANGE OF 1500 AND 3000
USE EMPLOYEE;
SELECT *
FROM EMP
WHERE SAL BETWEEN 1500 AND 3000;

-- WAQTD DETAILS OF EMPLOYEES WHO ARE EARNING SALARY IN THE BETWEEN OF 1500 AND 3000
SELECT *
FROM emp
WHERE SAL between 1501 AND 2999;
          