-- ORDER BY:
--    *IT IS USED TO ARRANGE THE RESULT TABLE RECORDS IN ASSENDING OR DESCENDING ORDER
--    *TO ARRANGE THE RECORDS IN ASSENDING ORDER WE WE USE THE KEYWORD ASC AND DECENDING ORDER WE USE DESC.
--    *ORDER BY CLAUSE EXECUTES AFTER THE EXECUTION OF SELECT CLAUSE.
--    *THIS WILL MAKECHANGES ONLY IN THE RESULT TABLE

-- SYNTEX:                                                               SYNTEX:
--   SELECT  */COL_NAME/EXP---------------->3                            SELECT GROUP_FUNCTION/GROUP_BY_EXPRESSION---------->5
--   FROM    TAB_NAME---------------------->1                            FROM    TAB_NAME----------------------------------->1   
--   [WHERE  <FILTER_CONDITIONS>]---------->2                            [WHERE  <FILTER_CONDITIONS>]----------------------->2 
--   ORDER BY COL_NAME/EXP----------------->4                            GROUP BY COL_NAME/EXP----------------------------->3
-- 																		 HAVING <FILTER_GROUP_CONDITION>-------------------->4
--                                                                       ORDER BY COL_NAME/EXP------------------------------>6

-- WAQTD SAL OF ALL THE EMPLOYEES IN DESC ORDER  
USE EMPLOYEE;
SELECT SAL
FROM EMP
ORDER BY SAL desc;

-- WAQTD SAL OF ALL THE EMPLOYEES IN DESC ORDER  
SELECT SAL
FROM EMP
ORDER BY SAL ASC;

-- WAQTD NAMES OF ALL THE EMPLOYEES HAVING CHARACTER A IN THEIR NAME IN DESC ORDER 
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '%A%'
ORDER BY ENAME DESC;

-- WAQTD DETAILS OF ALL THE EMPLOYEES AND ARRANGE RECORDS IN DESCENDING ORDER ACCORDING TO DEPTNO
SELECT *,DEPTNO
FROM EMP
ORDER BY DEPTNO DESC;

-- WAQTD ANNUAL SALARY OF ALL THE EMPLOYEES IN DESC ORDER
SELECT SAL*12 "ANNUAL SALARY"
FROM EMP
ORDER BY "ANNUAL SALARY" DESC;

-- WAQTD NO OF EMPLOYEES WORKING IN EACH DEPT AND ARRANGE THE RECORDS ACCORDING TO COUNT IN DESC ORDER
SELECT COUNT(*),DEPTNO
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO DESC;

-- WAQTD DEPTNO OF EMPLOYEES IN ASC ORDER AND SAL IN THE DEPT IN DESC ORDER
SELECT DEPTNO,SAL
FROM EMP
ORDER BY DEPTNO ASC,SAL DESC;

-- WAQTD COMISSION OF EMPLOYEES IN THE ASC ORDER
SELECT COMM
FROM EMP
ORDER BY COMM ASC;

-- WAQTD COMISSION OF EMPLOYEES IN THE DESC ORDER
SELECT COMM
FROM EMP
ORDER BY COMM DESC;
