CREATE DATABASE department;
USE department;
CREATE TABLE DEPT (
    DEPTNO INT,
    DNAME VARCHAR(20),
    LOC VARCHAR(20)
);
INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

SELECT * FROM DEPT;


-- assignement:
-- 1.WAOTD NaME OF The EMPLOYEES EARNING MORE THAN
-- ADAMS
USE EMPLOYEE;
SELECT ENAME
FROM EMP
WHERE SAL >  (SELECT SAL
			FROM EMP
            WHERE ENAME = 'ADAMS');
-- 2.WaQTD NAME ANd SALary OF THE EMPLOYEES EARNING
-- LESS THAN KING
SELECT ENAME , SAL
FROM EMP
WHERE SAL <(SELECT SAL
			FROM EMP
            WHERE ENAME = 'KING');
-- 3.WAOTd NAMe and deptno of the eMPLOYEES iF THEY ARE
-- WOrkING IN THE SAME DEPT AS JONES
SELECT ENAME,DEPTNO
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM EMP
                WHERE ENAME = 'JONES');
-- 4.WAOTD NaME AnD JOb OF aLL THE EMPLOYEES WORKING
-- IN THE SAME DESIGNATION AS JAMES
SELECT ENAME,JOB
FROM EMP
WHERE JOB = (SELECT JOB
			FROM EMP
            WHERE ENAME = 'JAMES');
-- 5.WAOtd EMPNO And eNAMe along with ANNUAL SALARY
-- oF aLL THEeMPLOYEES iF THEIR ANNUAL SALARY IS
-- GREATER THAN WARDS ANNUAL SALARY
SELECT ENAME,EMPNO,SAL*12 "ANNUAL_SALARY"
FROM EMP
WHERE SAL*12 > (SELECT SAL*12
				FROM EMP
                WHERE ENAME = 'WARD');
-- 6. W aOTd NaMe and HiRedate OF THE EMPLOYEES iF THEY
-- Are HiED BEFORE SCOTT
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE <(SELECT HIREDATE
				FROM EMP
                WHERE ENAME = 'SCOTT');
-- 7.W AOTd NaMe And hiredaTe OF THE EMPLOYEES iF THEY
-- ARe HIRED AFTeR THE PRESIDENT
SELECT ENAME,HIREDATE
FROM EMP 
WHERE HIREDATE > (SELECT HIREDATE
			     FROM EMP
                 WHERE JOB = 'PRESIDENT');
-- 8.WaQTD NAME and saL oF the eMPLOYEE iF THEy ARE
-- EARNING SAL leSS THAN The eMPLOyEE WHOS EMPNO IS 7839
SELECT ENAME,SAL
FROM EMP
WHERE SAL <(SELECT SAL
			FROM EMP
            WHERE EMPNO = 7839);
-- 9.W aQTD aLL THE DetaILs OF THE EMPLOYEES IF THE
-- EMPLOYEES ARe Hired BeFORE MILLER
SELECT *
FROM EMP
WHERE HIREDATE <(SELECT HIREDATE
				FROM EMP
                WHERE ENAME = 'MILLER');
-- 10.WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF
-- eMPLOYEeS Are earning MORE THAN ALLEN
SELECT ENAME,EMPNO
FROM EMP
WHERE SAL > (SELECT SAL 
			FROM EMP
            WHERE ENAME = 'ALLEN');
-- 11.WAQTD ENAME and saLary of aLL ThE EMPLOYEES WHO
-- are earning more than MiLLer but LESS THAN ALLEN
SELECT ENAME,SAL
FROM EMP
WHERE SAL >(SELECT SAL
			FROM EMP
			WHERE ENAME = 'MILLER') AND SAL <(SELECT SAL
											FROM EMP
                                            WHERE ENAME = 'ALLEN');
-- 12.WAQTD aLL The detAiLs OF THE EMPLOYEES WORKING IN
-- DEPT 20 ANd WorkiNg iN THE SAME DESIGNATION AS SMITH
SELECT *
FROM EMP
WHERE DEPTNO = 20 AND JOB =(SELECT JOB 
							FROM EMP
                            WHERE ENAME = 'SMITH');
-- 13.WaTD aLL THe DeTAILs OF THE EMPLOYEES WORKING AS
-- MANAGER IN THE SAME DEPT AS TURNER
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO =(SELECT DEPTNO
									FROM EMP
                                    WHERE ENAME = 'TURNER');
-- 14.WAQTD NaME and hiredate OF THE EMPLOYEES HIRED
-- aFTeR 1980 AND BEFORE KING
SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE > 1980-01-01 AND HIREDATE < (SELECT HIREDATE
								            FROM EMP
                                            WHERE ENAME = 'KING');
-- 15.WAOTD NAME ANd SAL aLong WitTH ANNUAL SAL FOR ALL
-- EMPLOYEES WHOS SAL IS LESS THAN BLakE AND MORE THAN
-- 3500
SELECT ENAME,SAL,SAL*12 "ANNUAL SALARY"
FROM EMP
WHERE SAL >(SELECT SAL
				 FROM EMP
                 WHERE ENAME = 'BLAKE') AND  SAL <3500;
-- 16.WAQTD ALL THE DETAILS OF EMPLoyEES WHO EARN MORE
-- THAN SCOTT BUT LESS THAN KING
SELECT *
FROM EMP
WHERE SAL BETWEEN (SELECT SAL
				FROM EMP
                WHERE ENAME = 'SCOTT') AND (SELECT SAL
											FROM EMP
                                            WHERE ENAME = 'KING');
-- 17.WaOTD NAME OF THe EMPLOYEES WHOS NAME STARTS
-- wiTH 'a' aNd workS iN THE SAME DEPT AS BLAKE
SELECT ENAME 
FROM EMP
WHERE ENAME LIKE 'A%' AND (SELECT DEPTNO
							FROM EMP
                            WHERE ENAME = 'BLAKE');
-- 18.WaOTD NAME AnD COMM iF EMPLOYEES EARN COMISSION
-- AND Work in the SAME DESIGNATION AS SMITH
SELECT ENAME,COMM
FROM EMP
WHERE COMM > 0 AND (SELECT JOB
					FROM EMP
                    WHERE ENAME = 'SMITH');
-- 19.WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS
-- CLERK IN THE SaME dEPT AS TURNER
SELECT *
FROM EMP
WHERE JOB = 'CLERK' AND DEPTNO =(SELECT DEPTNO
								FROM EMP
                                WHERE ENAME = 'TURNER');
-- 20. W AQTD ENAME, SAl and desiGNaTiON OF THE EMPLOYEES
-- WHOS ANNUAL SaLarY is MORE THAN SMITH AND LESS THAN
-- KING.
SELECT ENAME,SAL,JOB
FROM EMP
WHERE SAL*12 between (SELECT SAL*12+1
					 FROM EMP
                     WHERE ENAME = 'SMITH') AND (SELECT SAL*12-1
												FROM EMP
                                                WHERE ENAME = 'KING');