-- WAQTD DETAILS OF EMPLOYEES WHO IS EARNING MAXIMUM SALARY
USE EMPLOYEE;
SELECT *
FROM EMP
WHERE SAL = (SELECT MAX(SAL)
			FROM EMP);
            
-- WAQTD DETAILS OF EMPLOYEES WHO IS HIRED FIRST
SELECT *
FROM EMP
WHERE HIREDATE =(SELECT MAX(HIREDATE) 
				FROM emp);
-- WAQTD DETAILS OF EMPLOYEES WHO HIRED LAST
SELECT *
FROM EMP
WHERE HIREDATE =(SELECT MIN(HIREDATE) 
				FROM emp);
-- WAQTD MANAGER OF SMITH
SELECT * FROM EMP;
SELECT ENAME 
FROM EMP
WHERE EMPNO =(SELECT MGR
			FROM EMP
            WHERE ENAME = 'SMITH');
-- WAQTD NAMES OF EMPLOYEES REPORTING TO THE KING
SELECT ENAME 
FROM EMP
WHERE MGR IN (SELECT EMPNO
			FROM EMP
            WHERE ENAME ='KING');
-- WAQTD DETAILS OF ALL THE MANAGERS WHO ARE HAVING A IN THEIR NAME
SELECT *
FROM EMP
WHERE MGR IN(SELECT EMPNO
			FROM EMP);
-- WAQTD MANAGER SAL OF A KING
SELECT SAL
FROM EMP
WHERE EMPNO = (SELECT MGR
			FROM EMP
            WHERE ENAME = 'KING');
-- WAQTD DETAILS OF EMPLOYEES IFTHEY ARE REPORTING TO A PERSON WHO IS EARNING SALARY MORE THAN 2000
SELECT *
FROM EMP
WHERE EMPNO IN (SELECT MGR
			 FROM EMP
             WHERE SAL > 2000);
-- WAQTD DETALIS OF 2ND MAX SAL OF EMP
SELECT MAX(SAL)
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
			FROM EMP);