-- ASSIGNMENT ON INNER JOIN


-- 1.NaMe OF the emPLoyee aNd his LoCAtiON oF ALL THE EMPLOYEES.
SELECT ENAME,LOC
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;
-- 2.WaQTD DNAME anD SaLaRY for aLl THE EMPLOYEE WORKING IN
-- ACCOUNTING.
SELECT DNAME,SAL
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME = 'ACCOUNTING';
-- 3.WAQTD dNAME AND ANNUAL SALaRY FOR ALL
SELECT DNAME,SAL*12 "ANNUAL SALARY"
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;
-- 3.WAQTD DNAME AND ANNUAL SALARY FOR ALL
-- EMPLOYEES WHOS SALARY IS MORE THAN 2340
SELECT DNAME,SAL*12 "ANNUAL SALARY"
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL > 2340;
-- 4.WAOTD ENAME AND dNaME FOR EMPLOYEES HAVING
-- CAHARACTER 'A' IN THEIR DNAME
SELECT ENAME,DNAME
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME LIKE '%A%';
-- 5.WaQTD ENaME aND dNAME FOR ALL THE EMPLOYEES
-- WORKING AS SALESMAN
SELECT ENAME,DNAME
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'SALESMAN';
-- 6.WAdTD DNaME ANd JOB FOR ALL THE EMPLOYEES WHOS
-- JOB AND DNAME STARTS WITH CHARACTER 'S'
SELECT DNAME,JOB
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME LIKE 'S%';
-- 7.WAQTD DNAME AND MGR NO FOR EMPLOYEES
-- REPORTING TO 7839
SELECT DNAME,MGR
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMPNO = 7839;
-- 8.WAOTD DNAME ANd HIREdATE FOR EMPLOYEES HIRED
-- AFTER 83 INTO ACCOUNTING OR RESEARCH DEPT
SELECT DNAME , HIREDATE 
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO 
WHERE DNAME IN ('ACCOUNTING','RESEARCH') AND HIREDATE >(31-12-1983);
-- 9.WAoTd enaMe and dnaMe of THE EMPLOYEES WHO
-- ARE GETTING COMM IN DEPT 10 OR 30
SELECT ENAME,DNAME
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE COMM IS NOT NULL AND DEPT.DEPTNO IN(10,30);
-- 10.WAQTD DNAME AND EMPNO FOR ALL THE EMPLOYEES WHO'S EMPNO
-- ARE (7839,7902) AND ARE WORKING IN LOC NEW YORK.
SELECT DNAME ,EMPNO
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMPNO IN(7839,7902) AND LOC = 'NEW YORK';