-- WAQTD DETAILS OF EMPLOYEES WORKING IN RESREARCH DEPT
SELECT *
FROM employee.EMP
WHERE DEPTNO =(SELECT DEPTNO
				FROM department.dept
                WHERE DNAME = 'RESEARCH');
-- WAQTD DETAILS OF EMPLOYEES WORKING IN NEW YORK
SELECT *
FROM employee.EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM department.dept
                WHERE LOC = 'NEW YORK');
-- WAQTD DETAILS OF EMPLOYEES WHO ARE EARNING SAL MORE THAN ALLEN IN ACCOUNTING DEPT
SELECT *
FROM employee.EMP
WHERE SAL > (SELECT SAL
			FROM employee.emp
            WHERE ENAME = 'ALLEN') AND DEPTNO = (SELECT DEPTNO
												FROM department.dept
                                                WHERE DNAME = 'ACCOUNTING');
-- WAQTD DETAILS OF EMPLOYEES HIRED BEFORE SCOTT IN DALLAS
SELECT *
FROM employee.emp
WHERE HIREDATE < ( SELECT HIREDATE
				FROM employee.emp
                WHERE ENAME = 'SCOTT') AND DEPTNO = (SELECT DEPTNO
													FROM department.dept
                                                    WHERE LOC = 'DALLAS');

                
                
-- SUBQUERRY:
--    SUBQUERRY ARE CLASSIFIED INTO TWO:
--    *SINGLEROW SUBQUERRY------------------> RETURNS SINGLE VALUE OR SINGLE ROW
--    *MULTIROW SUBQUERRY-------------------> RETURNS MORE THAN ONE VALUE OR MORE THAN ONE ROW

-- EXAMPLE:
-- WAQTD DEPTNAME OF ALL THE MANAGERS
SELECT DNAME 
FROM department.dept
WHERE DEPTNO IN (SELECT DEPTNO
				FROM employee.EMP
                WHERE JOB = 'MANAGER');
                
-- WAQTD DETAILS OF ALL THE EMPLOYEES WORKING IN NEW YORK AND CHICAGO
SELECT *
FROM employee.emp
WHERE DEPTNO IN(SELECT DEPTNO
				FROM department.dept
                WHERE LOC IN ('NEW YORK','CHICAGO'));
                
                
-- SUBQUERRY OPERATORS:
-- ALL:
-- THIS OPERATOR RETURNS TRUE WHEN ALL THE GIVEN BY A SUBQUERRY SATISFIES THE CONDITION
-- ANY:
-- THIS IS A SUBQUERRY OPERATOR WHICH RETURNS WHEN ANY ONE OF THE VALUES GIVEN VALUES SATISFIED THE CONDITION


-- WAQTD DETAILS OF EMPLOYEES WHI ARE EARNING SALARY MORE THAN ALL THE MANAGERS
SELECT *
FROM employee.EMP
WHERE SAL >ALL (SELECT SAL
			FROM employee.emp
            where JOB = 'MANAGER');

-- WAQTD DETAILS WHO ARE EARNING SALARY ATLEAST MORE THAN ONE MANAGER
SELECT *
FROM employee.emp
WHERE SAL > ANY(SELECT SAL
				FROM employee.emp
                WHERE JOB = 'MANAGAER');
-- WAQTD DETAILS OF EMPLOYEES HIRED AFTER ALL THE EMPLOYEES OF DEPT 10
SELECT *
FROM employee.emp
WHERE HIREDATE > ALL  (SELECT HIREDATE 
						FROM employee.emp
                        WHERE DEPTNO = 10);
-- WAQTD DETAILS OF EMPLOYEES WHO ARE HIRED BEFORE BEFORE ALL THE EMPLOYEES OF DEPT 10
SELECT *
FROM employee.emp
WHERE HIREDATE < ALL  (SELECT HIREDATE 
						FROM employee.emp
                        WHERE DEPTNO = 10);