-- JOINS:
--   IT IS THE PROCESS OF RETRIVING DATA FROM MULTIPLE TABLES SIMULTINOUSLY
--   THE JOINS ARE DIVIDED INTO:
--       *CARTASION JOIN/CROSS JOIN
--       *INNER JOIN/EQUI JOIN
--       *NATURAL JOIN
--       *OUTER JOIN
--           ->LEFT OUTER JOIN
--           ->RIGHT OUTER JOIN
--           ->FULL OUTER JOIN
-- 	 *SELF JOIN
--      
--      
--      CROSS JOIN:
--          IN THESE TYPE OF JOIN THE RECORD FROM ONE TABLE WILL BE MERGED ALL THE RECORDS OF ANOTHER TABLE
--          
--          NO.OF COLUMN --->TAB1 + TAB2
--          NO.OF ROWS  ----> TAB1*TAB2
--          
--          SYNTAX:
--          ANSI:
--          SELECT */COL_NAME/EXP
--          FROM TAB_NAM1 CROSS JOIN TAB_NAME2;
--          
--          ORACLE:
--          SELECT */COL_NAME/EXP
--          FROM TAB_NAM1,TAB_NAME2;

USE EMPLOYEE;
SHOW SCHEMAS;
USE DEPARTMENT;

-- ANSI: 
SELECT *
FROM EMP CROSS JOIN department.dept;

-- ORACLE:
SELECT *
FROM EMP,department.dept;



-- EQUI JOIN:
--   IT IS USED TO DISPLAY ONLY MATCHING RECORDS FROM THE TABLE

-- SYNTAX:

-- ANSI:
-- SELECT */COL_NAME/EXP
-- FROM TAB_NAME1 EQUI JOIN TAB_NAME2
-- ON <JOIN_CONDITIONS>
-- [WHERE <FILTER_CONDITIONS>]

-- ORACLE:
-- SELECT */COL_NAME/EXP
-- FROM TAB_NAME1 EQUI , TAB_NAME2
-- WHERE JOIN_CONDITIONS [AND FILTER CONDITIONS]

-- WAQTD ENAME ALONG WITH THEIR DEPARTMRNT NAME
-- ANSI:
SELECT ENAME
FROM employee.emp INNER JOIN department.dept
ON EMP.DEPTNO = dept.DEPTNO;
-- ORACLE:
SELECT ENAME 
FROM EMP , department.dept
WHERE EMP.DEPTNO = DEPT.DEPTNO;
-- WAQTD NAME,SALRY,LOCATION OF ALL THE EMPLOYEES WHO ARE EARNING SALARY MORE THAN 1500
-- ANSI:
SELECT ENAME,SAL,LOC
FROM employee.EMP INNER JOIN department.dept
ON EMP.DEPTNO = dept.DEPTNO
WHERE SAL > 1500;
-- ORACLE: 
SELECT ENAME,SAL,LOC
FROM employee.EMP INNER JOIN department.dept
WHERE EMP.DEPTNO = DEPT.DEPTNO AND SAL > 1500;
