-- CASE 2:
--      WHENEVER THE DATA TO BE RETRIVE AND CONDITION TO BEEXECUTED FROM ANOTHER TABLE.
--      THEN THE SECOND CASE HAS BEEN USED

-- WAQTD DEPARTMENT NAME OF EMPLOYEES WHOSE NAME IS KING
SELECT DNAME
FROM department.dept
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM employee.emp
    WHERE ENAME = 'KING'
);
-- WAQTD  DEPARTMENT NAME AND LOCATION OF SMITH
SELECT DNAME,LOC
FROM department.dept
where DEPTNO=(SELECT DEPTNO
			FROM employee.EMP
            WHERE ENAME = 'SMITH');