-- WAQTD ENAME,DNAME FOR ALL THE EMPLOYEES WHO ARE WORKING IN ACCOUNTING DEPT
select ENAME,DNAME
FROM employee.emp INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME = 'ACCOUNTING';
-- WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THE LOC IF THE EMPLOYEES ARE EARNING BETWEEN 2000 AND 3000
SELECT EMP.* , LOC
FROM department.DEPT INNER JOIN employee.emp
ON DEPT.DEPTNO = EMP.DEPTNO 
WHERE SAL between 2001 AND 2999;
-- WAQTD ENAME,SAL AND DNAME FOR ALL THE EMPLOYEES HIRED AFTER SMITH
SELECT ENAME,SAL,DNAME
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE HIREDATE >(SELECT HIREDATE
                 FROM EMP
                 WHERE ENAME = 'SMITH');
-- WAQTD ENAME,DNAME FOR ALL THE EMPLOYEES WHO ARE WORKING AS A MANAGER IN DEPT 20
SELECT ENAME,DNAME
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'MANAGER' AND DEPT.DEPTNO = 20;
-- WAQTD ENAME,DNAME,SAL,LOC,DEPTNO AND HIREDATE FOR ALL THE EMPLOYEES WORKING IN THE DEPT RESEARCH OR SALES
SELECT ENAME,DEPT.DNAME,SAL,LOC,EMP.DEPTNO,HIREDATE
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = EMP.DEPTNO
WHERE DEPT.DNAME = 'RESEARCH' OR DEPT.DNAME = 'SALES';

-- NATURAL JOIN():
-- NATURAL JOIN IS HAVING A TWO BEHAVIOURS.THEY ARE:
-- * IT ACTS LIKE INNER JOIN WHENEVER THERE IS AN CONNECTION OR RELATION BETWEEN THE TABLES
-- * IT ACTS LIKE A CROSS JOIN WHENEVER THERE IS NO RELATION OR CONNECTION BETWEEN TWO TABLES

CREATE DATABASE department;
USE department;
CREATE TABLE dept (
    DEPTNO INT,
    DNAME VARCHAR(20),
    LOC VARCHAR(20)
);
INSERT INTO dept (DEPTNO, DNAME, LOC) VALUES
(10, 'ACCOUNTING', 'NEW YORK'),
(20, 'RESEARCH', 'DALLAS'),
(30, 'SALES', 'CHICAGO'),
(40, 'OPERATIONS', 'BOSTON');
SELECT * FROM dept;


select *
from employee.emp natural join department.dept ;
