-- SELF JOIN:
--   JOINING THE SAME TWO TABLES (OR) A TABLE JOINING ITELF IS KNOWN AS SELF JOIN


-- QUESTIONS:
  --  WAQTD ENAME,SALARY AND THEIR MANAGER NAME IF EMPLOYEES ARE EARNING SALARY MORE THAN 1500
--   ANSI:
SELECT E1.ENAME, E1.SAL, E2.ENAME AS MANAGER
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.SAL > 1500;

-- ORACLE:
SELECT E1.ENAME,E1.SAL,E2.ENAME AS MANAGER 
FROM employee.EMP E1,employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND (E1.SAL > 1500);
--    WAQTD ENAME ALONG WITH THEIR MANAGER NAME IF MANAGER NAME IS HAVING CHARACTER A 
-- ANSI:
SELECT E1.ENAME,E2.ENAME "MANAGER"
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E2.ENAME LIKE '%A%';
-- ORACLE:
SELECT E1.ENAME , E2.ENAME "MANAGER"
FROM employee.EMP E1, employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND (E2.ENAME LIKE '%A%');
--    WAQTD ENAME,HIREDATE ALONG WITH MANAGER NAME AND HIREDATE IF EMPLOYEES ARE HIRED BEFORE MANAGER
-- ANSI:
SELECT E1.ENAME,E1.HIREDATE,E2.ENAME,E2.HIREDATE
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.HIREDATE < E2.HIREDATE;
-- ORACLE:
SELECT E1.ENAME,E1.HIREDATE,E2.ENAME,E2.HIREDATE
FROM employee.EMP E1, employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND (E1.HIREDATE < E2.HIREDATE);




-- ASSIGNMENT ON SELF JOIN:


-- 1.WAOTD NAME OF THE EMPLOYEE AND HIS MANAGER'S NAME IF
-- EMPLOYEE IS WORKING AS CLERK
-- ANSI:
SELECT E1.ENAME,E1.HIREDATE,E2.ENAME
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.JOB = 'CLERK';
-- ORACLE:
SELECT E1.ENAME,E1.HIREDATE,E2.ENAME
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND E1.JOB = 'CLERK';
-- 2.WAOTD NAME OF THE EMPLOYEE AND MANAGER'S DESIGNATION IF
-- MANAGER WORKS IN DEPT 10 OR 20
-- ANSI:
SELECT E1.ENAME,E2.JOB
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E2.DEPTNO IN(10,20);
-- ORACLE:
SELECT E1.ENAME,E2.JOB
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND E2.DEPTNO IN(10,20);
-- 3. WAQTD NAME OF THE EMP AND MANAGERS SALARY iF EMPLOYEE AND "
-- MANAGER BOTH EARN MORE THAN 2300
-- ANSI:
SELECT E1.ENAME ,E2.SAL 
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.SAL > 2300 AND E2.SAL > 2300;
-- ORACLE:
SELECT E1.ENAME ,E2.SAL 
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND (E1.SAL > 2300 AND E2.SAL > 2300);
-- 4.WAQTD EMP NAME AND MANAGER'S HIREDATE IF EMPLOYEE WAS HIRED
-- BEFORE 1982
-- ANSI:
SELECT E1.ENAME, E2.HIREDATE
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E2.HIREDATE < '1982-01-01';
-- ORACLE:
SELECT E1.ENAME, E2.HIREDATE
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND E2.HIREDATE < '1982-01-01';
-- 5.WAQTD EMP NAME AND MANAGER'S COMM IF
-- EMPLOYEE WORKS AS SALESMAN AND MANAGER WORKS IN DEPT 30
-- ANSI:
SELECT E1.ENAME , E2.COMM
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.JOB ='SALESMAN' AND E2.DEPTNO = 30;
-- ORACLE:
SELECT E1.ENAME , E2.COMM
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND (E1.JOB ='SALESMAN' AND E2.DEPTNO = 30);
-- 6.WAQTD EMP NAME AND MANAGER NAME AND THEIR SALARIES IF
-- EMPLOYEE EARNS MORE THAN MANAGER
-- ANSI:
SELECT E1.ENAME,E1.SAL,E2.ENAME,E2.SAL
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.SAL > E2.SAL;
-- ORACLE:
SELECT E1.ENAME,E1.SAL,E2.ENAME,E2.SAL
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND E1.SAL > E2.SAL;
-- 7.WAQTD EMP NAME AND HIREDATE_ MANAGER NAME
-- AND HIREDATE IF
-- MANAGER WAS HIRED BEFORE EMPLOYEE
-- ANSI:
SELECT E1.ENAME,E1.HIREDATE,E2.ENAME,E2.HIREDATE
FROM employee.EMP E1 JOIN employee.EMP E2 
ON E1.MGR = E2.EMPNO 
WHERE E1.HIREDATE > E2.HIREDATE;
-- ORACLE:
SELECT E1.ENAME,E1.HIREDATE,E2.ENAME,E2.HIREDATE
FROM employee.EMP E1 , employee.EMP E2 
WHERE E1.MGR = E2.EMPNO AND E1.HIREDATE > E2.HIREDATE;
-- 8.WAOTD EMP NAME AND MANAGER NAME IF BOTH ARE WORKING IN SAME
-- JOB
-- ANSI:
SELECT E1.ENAME,E2.ENAME
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.JOB = E2.JOB;
-- ORACLE:
SELECT E1.ENAME,E2.ENAME
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND E1.JOB = E2.JOB;
-- 9.WAQTD EMP NAME AND MANAGER NAME IF MANAGER IS WORKING AS
-- ACTUAL MANAGER
-- ANSI:
SELECT E1.ENAME,E2.ENAME
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E2.JOB = 'MANAGER';
-- ORACLE:
SELECT E1.ENAME,E2.ENAME
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND E2.JOB = 'MANAGER';
-- 10.WAQTD EMP NAME AND MANAGER NAME ALONG
-- WITH THEIR ANNUAL SAL ARIES IF EMPLOYEE WORKS IN DEPT 10, 20 AND
-- MANAGER'S SAL IS GREATER THAN EMPLOYEES SALARY
-- ANSI:
SELECT E1.ENAME,E2.ENAME,E2.SAL "ANNUAL SALARY"
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E1.DEPTNO IN(10,20) AND E2.SAL > E1.SAL;
-- ORACLE:
SELECT E1.ENAME,E2.ENAME,E2.SAL "ANNUAL SALARY"
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND (E1.DEPTNO IN(10,20) AND E2.SAL > E1.SAL);
-- 11.WAQTD EMPLOYEE'S NAME AND MANAGER'S DESIGNATION FOR ALL THE
-- EMPLOYEES
-- ANSI:
SELECT E1.ENAME,E2.JOB
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO;
-- ORACLE:
SELECT E1.ENAME,E2.JOB
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 12.WAQTD EMPLOYEE'S NAME AND MANAGER'S SALARY
-- FOR ALL THE EMPLOYEES IF MANAGER'S SALARY ENDS WITH 50
--   
-- ANSI:
SELECT E1.ENAME , E2.SAL
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO
WHERE E2.SAL LIKE '%50';
-- ORACLE: 
SELECT E1.ENAME , E2.SAL
FROM employee.EMP E1 JOIN employee.EMP E2
WHERE E1.MGR = E2.EMPNO AND E2.SAL LIKE '%50';