-- WAQTD ENAME,DEPTNO AND THEIR LOCATION WHO ARE WORKING IN DEPT 20
-- INNER JOIN/EQUI JOIN:
SELECT ENAME,DEPT.DEPTNO,LOC
FROM employee.EMP INNER JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DEPT.DEPTNO = 20;

-- NATURAL JOIN:
SELECT ENAME,DEPTNO,LOC
FROM employee.EMP natural JOIN department.DEPT
WHERE DEPTNO = 20;


-- OUTERJOINS:
-- *LEFT OUTER JOIN:
-- IT IS USED TO DISPLAY THE MATCHING RECORDS FROM BOTH THE TABLE AND UNMATCHING
-- RECORDS FROM THE LEFT TABLE

-- ANSI:
-- SYNTAX:
-- SELECT */COL_NAME/EXP
-- FROM TAB1_NAME LEFT JOIN TAB_NAME2
-- ON JOIN CONDITIONS
SELECT *
FROM employee.EMP left JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- ORACLE:
-- SYNTAX:
-- SELECT */COL_NAME/EXP
-- FROM TAB1_NAME,TAB_NAME2 
-- WHERE TAB_NAME1.COL_NAME = TAB_NAME2.COL_NAME (+);

SELECT *
FROM employee.EMP , department.DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO (+);

-- RIGHT OUTER JOIN:
-- IT IS USED TO DISPLAY THE MATCHING RECORDS FROM BOTH THE TABLE AND UNMATCHING
-- RECORDS FROM THE RIGHT TABLE

-- ANSI:
-- SYNTAX:
-- SELECT */COL_NAME/EXP
-- FROM TAB1_NAME RIGHT JOIN TAB_NAME2
-- ON JOIN CONDITIONS
SELECT *
FROM employee.EMP RIGHT JOIN department.DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- ORACLE:
-- SYNTAX:
-- SELECT */COL_NAME/EXP
-- FROM TAB1_NAME,TAB_NAME2 
-- WHERE TAB_NAME1.COL_NAME(+) = TAB_NAME2.COL_NAME ;

SELECT *
FROM employee.EMP , department.DEPT
WHERE EMP.DEPTNO (+) = DEPT.DEPTNO ;




-- FULL OUTER JOIN:
-- ITIS USED TO DISPLAY MATCHED RECORDS AS WELL AS UNMATCHED RECORDS FROM BOYH THE TABLES


-- ANSI:
-- SYNTAX:
--  SELECT */COL_NAME/EXPRESSION
--  FROM TAB_NAME1 FULL JOIN TAB_NAME2
--  WHERE TAB_NAME1.COL_NAME = TAB_NAME2.COL_NAME

-- EXAMPLE:
 SELECT *
 FROM employee.EMP FULL JOIN department.DEPT
 WHERE EMP.DEPTNO = DEPT.DEPTNO;