SHOW SCHEMAS;
SHOW TABLES FROM QSP;

-- RENAME:
-- THE NAME IS USED TO CHANGE THE NAME OF AN EXISTING TABLE

-- SYNTAX:
--   RENAME TABLE EXISTING_TABLE_NAME TO NEWNAME

use QSP;
RENAME TABLE wine_shop TO TASMAC;



-- TRUNCATE:
-- THIS STATEMENT IS USED TO REMOVE ALL THE RECORDS FROM THE TABLE AT A TIME PERMENTLY

-- SYNTAX:
-- TRUNCATE TABLE TABLE_NAME;

TRUNCATE TABLE TASMAC;


-- DROP:
--    THIS TABLE IS USED TO DELETE THE ENTIRE TABLE ALONG WITH THE RECORDS FROM THE DATABASE
--    THE DROPED TABLE WILL BE STORED IN THE RECYCLE BIN

DROP TABLE TASMAC;
ALTER TABLE customers 
DROP FOREIGN KEY IRFAN_FK;

-- PURGE:
--    IT IS USED TO REMOVE A TABLE FROM THE RECYCLE BIN
--    SYNTAX:
--    PURGE TABLE TABLE_NAME;
   
PURGE TABLE TASMAC;


-- ALTER:
--  THIS STATEMENT IS USED TO MODIRY THE STRUCTURE OF THE TABLE
--  
--  ADD A COLUMN:
--  SYNTAX:
 ALTER TABLE TASMAC
 ADD COMPLIMENT VARCHAR(20);
 

--  RENAME A COLUMN:
--  SYNTAX:
 ALTER TABLE TASMAC
 RENAME COLUMN PRICE TO VELAI;
 
--  TO MODIFY DATATYPE:
-- SYNTAX:
-- ALTER TABLE TABLENAME
-- MODIFY COL_NAME NEW_DATATYPE

ALTER TABLE TASMAC
MODIFY BRAND CHAR(30);

-- TO MODIFY NULL/NOT NULL
-- SYNTAX:
-- ALTER TABLE TABLE_NAME
-- MODIFY COL_NAME [EXISTING_DATATYPE] NULL/NOT NULL;

ALTER TABLE TASMAC
MODIFY QUANTITY varchar(10) NULL;


