-- JOINING MULTIPLE TABLES:


-- *WAQTD EMPLOYEE NAME ALONG WITH THEIR DEPT NAME
-- ANSI:
SELECT E1.ENAME,D1.DNAME
FROM employee.EMP E1 INNER JOIN department.DEPT D1
ON E1.DEPTNO = D1.DEPTNO;
-- ORACLE:
SELECT E1.ENAME,D1.DNAME
FROM employee.EMP E1 , department.DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO;
-- *WAQTD ENAME ALONG WITH THEIR MANAGER NAME
-- ANSI:
SELECT E1.ENAME,E2.ENAME
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO;
-- ORACLE:
SELECT E1.ENAME,E2.ENAME
FROM employee.EMP E1 , employee.EMP E2
WHERE E1.MGR = E2.EMPNO;
-- *WAQTD ENAME,MANAGER NAME AND MANAGERS MANAGER NAME
-- ANSI:
SELECT E1.ENAME,E2.ENAME "MANAGER",E3.ENAME "MANAGER'S MANAGER"
FROM employee.EMP E1 JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO JOIN employee.EMP E3
ON E2.MGR = E3.EMPNO;
-- ORACLE:
SELECT E1.ENAME,E2.ENAME "MANAGER",E3.ENAME "MANAGER'S MANAGER"
FROM employee.EMP E1,employee.EMP E2,employee.EMP E3
WHERE E1.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO;
-- *WAQTD ENAME, DEPT NAME ALONG WITH THEIR MANAGER NAME
-- ANSI:
SELECT E1.ENAME,D1.DNAME,E2.ENAME "MANAGER'S NAME"
FROM employee.EMP E1 INNER JOIN department.DEPT D1
ON E1.DEPTNO = D1.DEPTNO INNER JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO;
-- ORACLE:
SELECT E1.ENAME,D1.DNAME,E2.ENAME "MANAGER'S NAME"
FROM employee.EMP E1,department.DEPT D1,employee.EMP E2
WHERE E1.DEPTNO = D1.DEPTNO AND E1.MGR = E2.EMPNO;
-- *WAQTD ENAME,DEPT NAME, MANAGER NAME ALONG WITH THEIR LOCATION
-- ANSI:
SELECT E1.ENAME,D1.DNAME,E2.ENAME,D2.LOC
FROM employee.EMP E1 INNER JOIN department.DEPT D1
ON E1.DEPTNO = D1.DEPTNO INNER JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO INNER JOIN department.DEPT D2
ON D2.DEPTNO = E2.DEPTNO;
-- ORACLE:
SELECT E1.ENAME,D1.DNAME,E2.ENAME,D2.LOC
FROM employee.EMP E1 , department.DEPT D1 , employee.EMP E2,department.DEPT D2
WHERE E1.DEPTNO = D1.DEPTNO AND E1.MGR = E2.EMPNO AND D2.DEPTNO = E2.DEPTNO;
-- *WAQTD EMPLOYEE NAME THEIR DEPT NAME AND THEIR MANAGER NAME IF EMPLOYEES ARE HIRED IN THE RANGE OF 1981 AND 1985 AND THEIR MANAGERS WORKING IN NEW YORK
-- ANSI:
SELECT E1.ENAME,D1.DNAME,E2.ENAME "MANAGER NAME"
FROM employee.EMP E1 INNER JOIN department.DEPT D1
ON E1.DEPTNO = D1.DEPTNO INNER JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO INNER JOIN department.DEPT D2
ON E2.DEPTNO = D2.DEPTNO
WHERE E1.HIREDATE BETWEEN '1981-01-01' AND '1985-12-31' AND D2.LOC = 'NEW YORK';
-- ORACLE:
SELECT E1.ENAME,D1.DNAME,E2.HIREDATE "MANAGER NAME"
FROM employee.EMP E1, department.DEPT D1,employee.EMP E2, department.DEPT D2
WHERE E1.DEPTNO = D1.DEPTNO AND E1.MGR = E2.EMPNO AND E2.DEPTNO = D2.DEPTNO AND E1.HIREDATE BETWEEN '1981-01-01' AND '1985-12-31' AND D2.LOC = 'NEW YORK';
-- *WAQTD EMPLOYEE NAME, THEIR DEPTNAME,MANAGER NAME AND THEIR LOCATION AND MANAGERS MANAGER NAME WITH THEIR LOCATION IF EMPLOYEES ARE HIRED IN 1981 AND EMPLOYEES 
--   DEPTNAME HAVING CHARACTER 'A' AND MANAGERS EARNING SALARY MORE THAN EMPLOYEES AND MANAGERS LOCATION STARTING WITH C AND MANAGERS MANAGER EARNING COMESSION 
--   AND MANAGERS MANAGER LOCATION HAVING MORE THAN 4 CHARACTERS
-- ANSI:
SELECT E1.ENAME,D1.DNAME,E2.ENAME,D2.LOC,E3.ENAME,D3.LOC
FROM employee.EMP E1 INNER JOIN department.DEPT D1
ON E1.DEPTNO = D1.DEPTNO INNER JOIN employee.EMP E2
ON E1.MGR = E2.EMPNO INNER JOIN department.DEPT D2
ON E2.DEPTNO = D2.DEPTNO INNER JOIN employee.EMP E3
ON E2.MGR = E3.EMPNO INNER JOIN department.DEPT D3
ON E3.DEPTNO = D3.DEPTNO
WHERE E1.HIREDATE BETWEEN '1981-01-01' AND '1981-12-31' AND D1.DNAME LIKE '%A%' AND E2.SAL > E1.SAL AND D2.LOC LIKE 'C%' AND E3.COMM IS NOT NULL 
AND D3.LOC LIKE '____';
-- ORACLE:
SELECT E1.ENAME,D1.DNAME,E2.ENAME,D2.LOC,E3.ENAME,D3.LOC
FROM employee.EMP E1 , department.DEPT D1 , employee.EMP E2 , department.DEPT D2 , employee.EMP E3 , department.DEPT D3
WHERE E1.DEPTNO = D1.DEPTNO AND E1.MGR = E2.EMPNO AND E2.DEPTNO = D2.DEPTNO AND E2.MGR = E3.EMPNO AND E3.DEPTNO = D3.DEPTNO 
AND E1.HIREDATE BETWEEN '1981-01-01' AND '1981-12-31' AND D1.DNAME LIKE '%A%' AND E2.SAL > E1.SAL AND D2.LOC LIKE 'C%' AND E3.COMM IS NOT NULL 
AND D3.LOC LIKE '____';