-- CORELATED SUBQUERRY:
--   A QUERRY WRITTEN INSIDE ANOTHER QUERRY SUCH A WAY THAT BOTH INNER QUERRY AND OUTER QUERRY 
--   ARE DEPENDENT ON EACH OTHER OR INTERDEPENDENT IS KNOWN IS KNOWN AS CORELATED SUBQUERRY

-- WORKING PRINCIPLE:

-- HERE WE HAVE TWO QUERRYS.THEY ARE:
-- *OUTER QUERRY
-- *INNER QUERRY

-- BETWEEN THESE TWO QUERRYS OUTERQUERRY EXECUTES FIRST AND GIVES PARTIAL OUTPUT
-- THE OUTPUT OF OUTERQUERRY IS GIVENAS INPUT TO THE INNER QUERRY
-- THE INNER QUERRY EXECUTES AND GIVES THE HALF OF THE OUTPUT TO THE OUTER QUERRY BY USING THE PARTIAL OUTPUT
-- THE OUTPUT OF INNER QUERRY IS GIVEN AS INPUT TO OUTER QUERRY
-- USING THIS INPUT OUTERQUERRY WILL EXECUTE AND GIVE THE FINAL OUTPUT
-- HERE OUTERQUERRY AND INNERQUERRY ARE INTERDEPENDENT ON EACH OTHER

-- WAQTD DEPTNAME IN WHICH EMPLOYEES ARE WORKING
SELECT DNAME
FROM department.DEPT
WHERE DEPTNO IN (SELECT DEPTNO
				FROM employee.EMP
                WHERE EMP.DEPTNO = DEPT.DEPTNO);
                
-- WAQTD DEPTNAME IN WHICH EMPLOYEES ARE NOT WORKING
SELECT DNAME
FROM department.DEPT
WHERE DEPTNO NOT IN (SELECT DEPTNO
				     FROM employee.EMP
					WHERE EMP.DEPTNO = DEPT.DEPTNO);
                    
-- WAQTD DEPTNAME IN WHICH EMPLOYEES ARE WORKING
SELECT DNAME
FROM department.DEPT
WHERE exists (SELECT DNAME
			 FROM employee.EMP
             WHERE EMP.DEPTNO = DEPT.DEPTNO);
             
-- WAQTD DEPTNAME IN WHICH EMPLOYEES ARE NOT WORKING
SELECT DNAME
FROM department.DEPT
WHERE NOT exists (SELECT DNAME
			     FROM employee.EMP
				WHERE EMP.DEPTNO = DEPT.DEPTNO);