-- FINDING NTH MAX AND MIN SALARY BY USING PSUDOCOLUMNS:

-- WAQTD THIRD MAXIMUM SALARY
 SELECT SAL 
 FROM (SELECT ROWNUM AS SLNO , SAL
       FROM (SELECT DISTINCT SAL
             FROM EMP
             ORDER BY SAL DESC))
 WHERE SLNO = 3;

--    SAL
-- ------
--   2975

-- WAQTD THIRD MINIMUM SALARY
 SELECT SAL 
 FROM (SELECT ROWNUM AS SLNO , SAL
       FROM (SELECT DISTINCT SAL
             FROM EMP
             ORDER BY SAL ASC))
 WHERE SLNO = 3;
 
 
 
 -- DATA DEFINITION LANGUAGE:
--    IT IS USED TO CREATE OR MODIFY STRUCTURE OF THE OBJECTS (TABLES OR VIEWS) IN THE DATABASE
--    THERE ARE FIVE STATEMENTS UNDER DATA DEFINITION LANGUAGE
--    *CREATE
--    *RENAME
--    *ALTER
--    *TRUNCATE
--    *DROP
--    
-- CREATE:
--    IT IS USED TO CREATE THE STRUCTURE OF OBJECTS IN THE DATABASE
--    
-- SYNTAX:
-- CREATE TABLE TABLE_NAME
-- (
-- COL_NAME1 DATATYPE [CONSTRAINTS]
-- COL_NAME2 DATATYPE [CONSTRAINTS]
-- COL_NAME3 DATATYPE [CONSTRAINTS]
-- .
-- .
-- .
-- .
-- COL_NAME(N) DATATYPE [CONSTRAINTS]
-- )

CREATE DATABASE QSP;
USE QSP;
CREATE TABLE WINE_SHOP
(SLNO numeric(3) NOT null check(SLNO>0) primary key,
BRAND VARCHAR(30) NOT NULL,
PRICE numeric(5,2) NOT NULL  check(PRICE>0),
QUANTITY varchar(10) NOT NULL,
SIDE_DISH varchar(10),
TYPE VARCHAR(30) NOT NULL
);

SELECT * FROM WINE_SHOP;



-- RELATION TABLE
USE QSP;
CREATE TABLE CUSTOMERS
(CID numeric(3) NOT NULL primary KEY,
CNAME varchar(30) NOT NULL,
PHNO numeric(10) NOT NULL check(length(PHNO)=10),
SLNO NUMERIC (3),
constraint IRFAN_FK foreign key(SLNO) REFERENCES WINE_SHOP(SLNO)
);

SELECT * FROM CUSTOMERS;


-- CREATE A TABLE THAT WHO ARE PLAYING BOTH INTERNATIONAL AND DOMESTIC
USE QSP;
CREATE TABLE INTERNATIONAL_PER
(JERSY_NO  numeric(3) CHECK(JERSY_NO<0) PRIMARY KEY,
PNAME VARCHAR(30) NOT NULL,
RUNS NUMERIC(4),
WICKETS numeric(3),
CATCHES NUMERIC(2),
AVG NUMERIC(4,2),
POTM NUMERIC(3)
);

CREATE TABLE DOMESTIC_PER
(   PNAME VARCHAR(30) NOT NULL,
    RUNS NUMERIC(4),
    WICKETS NUMERIC(3),
    CATCHES NUMERIC(2),
    AVG NUMERIC(4,2),
    POTM NUMERIC(3),
    JERSY_NO NUMERIC(3),
    CONSTRAINT FRKEY FOREIGN KEY (JERSY_NO) REFERENCES INTERNATIONAL_PER(JERSY_NO)
);

SELECT * FROM DOMESTIC_PER;

DESC DOMESTIC_PER;
DESC INTERNATIONAL_PER;



