USE QSP;
CREATE TABLE TRAINEER
(TNO NUMERIC(3) PRIMARY KEY NOT NULL CHECK(TNO>0),
TNAME VARCHAR(30) NOT NULL,
SUBJECT VARCHAR(30)
);
SELECT * FROM TRAINEER;

CREATE TABLE STUDENT
(SNO NUMERIC(3) PRIMARY KEY NOT NULL CHECK(SNO>0),
SNAME VARCHAR(30) NOT NULL,
TIMING timestamp 
);



-- TO DISPLAY ALL THE CONSTRAINTS ASSIGNED TO THE TABLE
-- SELECT *
-- FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
-- WHERE TABLE_NAME = 'STUDENT';


ALTER TABLE STUDENT
ADD TNO NUMERIC(3) ;


ALTER TABLE STUDENT
ADD constraint TID_FK foreign key(TNO) references TRAINEER(TNO);



-- DATA MANUPULATION LANGUAGE(DML):
   --  *IT IS USED TO MANIPULATE THE TABLES PRESENT IN THE DATABASE
--     *IN DATA MANIPULATION LANGUAGE WE HAVE THREE SUB STATEMENTS. THEY ARE:
--          *INSERT
--          *UPDATE
--          *DELETE

-- INSERT:-
-- THIS SATEMENT IS USED TO INSERT DATA (OR) VALUES INTO A TABLE

-- SYNTAX:
-- INSERT INTO TAB_NAME VALUES(VALUE1,VALUE2,VALUE3,VALUE4,_______VALUE N)
-- INSERT INTO TAB_NAME (COL1,COL2,COL3_______________COL N) VALUES(VALUE1,VALUE2,VALUE3,VALUE4,_______VALUE N)
-- INSERT INTO TAB_NAME VALUES (&COL1,&COL2,&COL3_______________&COL N)

INSERT INTO STUDENT VALUES (1, 'AAA', '2026-01-15 00:00:00');


INSERT INTO STUDENT (SNO, SNAME, TIMING)
VALUES (1, 'AAA', '2026-01-15 00:00:00');


INSERT INTO STUDENT VALUES (&SNO, &SNAME, &TIMING);
