-- TO FIND THE Nth MAXIMUM AND MINIMUM VALUES USING CO-RELATED SUBQUERRY

-- WAQTD 2ND MAX SAL
SELECT DISTINCT SAL
FROM EMPLOYEE.EMP E1
WHERE 2 IN (SELECT COUNT(DISTINCT SAL)
		    FROM employee.EMP E2
            WHERE E1.SAL <= E2.SAL);
            
-- WAQTD 2ND MIN SAL
SELECT DISTINCT SAL
FROM EMPLOYEE.EMP E1
WHERE 2 IN (SELECT COUNT(DISTINCT SAL)
		    FROM employee.EMP E2
            WHERE E1.SAL >= E2.SAL);
            
            
-- WAQTD DEALIS OF EMPLOYEES EARNING 1ST , 3RD AND 5TH MAX SAL
SELECT distinct SAL
FROM employee.EMP E1
WHERE (select count(distinct SAL)
	  FROM employee.EMP E2
      WHERE E1.SAL <= E2.SAL) IN (1,3,5);
      
	
-- WAQTD DEALIS OF EMPLOYEES EARNING 2ND , 4TH AND 6TH MIN SAL
SELECT distinct SAL
FROM employee.EMP E1
WHERE (select count(distinct SAL)
	  FROM employee.EMP E2
      WHERE E1.SAL >= E2.SAL) IN (2,4,6);
      
      
      
      
      
      
-- SET OPERATORS:
--  THE OPERATORS ARE USED TO COMBINE THE RESULT OF TWO OR MORE SELECT STATEMENTS
--  * LIST OF SET OPERATORS ARE:
--       UNION
--       UNION ALL
--       INTERSECT
--       MINUS
--       
--       
-- UNION:
--     IT IS USED TO COMBINE THE RESULT OF TWO OF THE QUERRY AND DISPLAY WITHOUT REAPITING VALUES
    SELECT DEPTNO 
    FROM employee.EMP
    UNION 
    SELECT DEPTNO
    FROM department.DEPT;
    
-- UNION ALL:
--     IT IS USED TO COMBINE THE RESULT OF TWO QUERRYS AND DISPLAY WITHOUT REMOVING THE REPEATED VALUES
    SELECT DEPTNO 
    FROM employee.EMP
    UNION ALL
    SELECT DEPTNO
    FROM department.DEPT;
    
-- INTERSECT:
--    IT WILL COMBINE THE RESULT OF TWO QUERRYS AND DISPLAY ONLY THE COMMON VALUES
     SELECT DEPTNO 
    FROM employee.EMP
    INTERSECT
    SELECT DEPTNO
    FROM department.DEPT;
    
-- MINUS:
--     IT IS USED TO DISPLAY UNCOMMON VALUES ONLY FROM THE FIRST RESULT
    SELECT DEPTNO 
    FROM employee.EMP
    MINUS
    SELECT DEPTNO
    FROM department.DEPT;