-- INSTR():
--    THIS FUNCTION IS USED TO GET THE INDEX POSITION OF A CHARACTER PRESENT IN A STRING
--    SYNTAX:
--    INSTR(ORIGINAL_STR,STRING,[POSITION],[OCCURANCE])
   
-- WAQTD NAME OF EMPLOYEES STARTING WITH S
   SELECT ENAME
   FROM employee.EMP
   WHERE instr(ENAME,'S',1)=1;
   
-- WAQTD NAME OF EMPLOYEES ENDING WITH S
   SELECT ENAME
   FROM employee.EMP
   WHERE INSTR(ENAME,'S',-1)=length(ENAME);
   
 --   MOD():
--      IT IS USED TO FIND THE REMAINDER OF TWO VALUES
-- SYNTAX:
-- MOD(ARG1,ARG2)
SELECT mod(10,2) , mod(17,2)
FROM DUAL;

-- ROUND():
--  IT IS USED TO ROUND OF DECIMAL VALUES TO THE NEAREST INTEGER VALUES
-- SYNTAX:
--   ROUND(NUMBER,[SCALE])

SELECT round(23.7)
FROM DUAL;

SELECT round(23.4)
FROM DUAL;

-- TURN():
--   IT IS USED TO ROUNDOFF THE DECIMAL VALUES
-- SYNTAX:
--  TURN(NUMBER,[SCALE])

 SELECT TRUNC(23.7,2)
 FROM DUAL;
  
  
 
     
   