-- VIEW:
--    A VIEW IS A VIRTUAL TABLE (or) IMAGINARY TABLE WHICH IS USED TO STORE THE RESULT OF A QUERRY
--    
--    SYNTAX:
--      CREATE VIEW VIEW_NAME
--      AS
--      SELECT STATEMENT;

USE EMPLOYEE;
CREATE VIEW IRFAAAN AS
SELECT ENAME, DEPTNO
FROM EMP;

SELECT *
FROM IRFAAAN;

UPDATE VIEW IRFAAAN SET DEPTNO = NULL WHERE ENAME = 'MILLER';

SELECT * FROM EMP;

-- NOTE:
--    IF WE MAKE ANY CHANGES ON THE VALUES PRESENT IN A VIEW. THESE CHANGES WILL BE REFLECTED IN THE 
--    ORIGINAL TABLE AND IF WE MAKE CHANGES IN THE THE ORIGINAL TABLE IT WILL BE REFLECTEDD IN THE VIEW

-- METRALIZED VIEW:
CREATE MATERIALIZED VIEW POORNA AS
SELECT ENAME, DEPTNO
FROM EMP;

UPDATE VIEW IRFAAAN SET DEPTNO = NULL WHERE ENAME = 'MILLER';

-- NOTE:
--    WE CANNOT PERFORM ANY DML OPERATIONS IN METRALIZED VIEW
   
-- DROPPING OF VIEW:
   DROP VIEW IRFAAAN;
   DROP METRALIZED VIEW POORNA;
   
   
-- WINDOW FUNCTION / ANALYTICAL FUNCTION:
--   ROW_NUMBER():
--   THIS FUNCTION WILL ASSIGNS SERIAL NUMBERS FOR ALL THE ROWS
--   RANK():
--   THIS FUNCTION ASSIGNS SAME RANK FOR THE SAME VALUES AND IT WILL SKIP THE SEQUENCE BY NUMBER OF TIES
--   DENSE_RANK():
--   THIS FUNCTION ASSIGNS SAME RANK FOR SAME VALUES AND CONTINUE THE SEQUENCE FOR THE NEXT ROW
  
  
--   QUERRY:

SELECT DEPTNO,SAL,row_number() OVER(ORDER BY SAL DESC) AS RN,
                  RANK() OVER(ORDER BY SAL DESC) AS R,
                  DENSE_RANK() OVER(ORDER BY SAL DESC) AS DR
FROM EMP;


-- WAQTD SECOND MAXIMUM SALARY FROM EACH DEPT

SELECT SAL, DEPTNO
FROM (
    SELECT SAL, DEPTNO,DENSE_RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS DR
    FROM EMP) AS sub
WHERE DR = 2;

  
     