-- SINGLE-ROW-MULTIFUNCTIONS:

--    LENGTH():
--      IT IS USED TO FIND THE NO.OF CHARACTERS PRESENT IN THE STRING
     
     SELECT LENGTH('POORNA')
     FROM DUAL;
     
--      WAQTD NAMES OF EMPLOYEES HAVING MORE THAN 4 CHARACTERS
SELECT ENAME,Length(ENAME)
FROM employee.EMP
WHERE length(ENAME)>4;

-- CONCAT:
--   IT IS USED TO COMBINE OR MERGE TWO STRINGS OR TWO COLUMNS
-- SYNTAX:

SELECT CONCAT ('HELLO','HI')
FROM DUAL;


SELECT CONCAT(ENAME, SAL)
FROM employee.EMP;
  
  
SELECT CONCAT(ENAME, CONCAT('  ',SAL))
FROM employee.EMP;
  
  
-- UPPER():
--    THIS FUNCTION IS USED TO CONVERT ALL THE CHARACTERS IN A STRING INTO UPPERCASE
   
   SELECT UPPER('poorna')
   from DUAL;
   
   -- LOWER():
--    THIS FUNCTION IS USED TO CONVERT ALL THE CHARACTERS IN A STRING INTO LOWERCASE
   
   SELECT LOWER('POORNA')
   from DUAL;
   
--    INITCAP():
-- SYNTAX:
-- SELECT INITCA('STRING')
--       THIS FUNCTION IS USED TO CONVERT FIRST CHARACTER IN STRING TO UPPER AND ALL THE REMAINING
--       ARE LOWER
   SELECT INITCAP('POORNA cHANDRA ')
   from dual;
   
--    WAQTD NAMES WHICH ARE PALONDROMES
SELECT ENAME
FROM employee.EMP
WHERE ENAME = reverse(ENAME);

-- REPLACE:
--    THIS FUNCTION IS USED TO REPLACE THE EXISTING CHARACTER IN A STRING WITH A NEW CHARACTERS
-- SYNTAX:
-- REPLACE(STRING,'EXIIISTING_CHAR',[NEW_CHAR]

SELECT ('POORNA','O','A')
FROM DUAL;

-- SUBSTR():
--   THIS FUNCTION IS USED TO EXTRACT A PART OF A STRING FROM THE ORIGINAL STRING
--   
--   SYNTAX:
--   SUBSTR(ORIGINAL_STRING,POSITION,[LENGTH]

SELECT substr('BRIYANI',-5,4)
FROM dual;

-- WAQTD NAME AND FIRST CHARACTER EMPLOYEE FROM TABLE 
SELECT substr(ENAME,1,1)
FROM EMP;

-- WAQTD NAME OF THE EMPLOYEE TABLE WITH NAME IS "S"
SELECT ENAME
FROM employee.EMP
WHERE substr(ENAME,1,1)='S';


   
   
   