-- WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH THEIR ANNUAL SALARY
USE EMPLOYEE;
SELECT EMP.* , SAL*12
FROM EMP;
-- WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH 10% HIKE OF THE SALARY
select EMP.*,SAL*12,SAL+SAL/10
FROM EMP;

-- ALLIAS:
-- * IT IS THE PROCESS OF GIVING ALTERNATIVE NAMES TO THE COLUMNS
-- *TO GIVE ALTERNATIVE NAMES WE USE KEYWORD "AS"
-- *WE CAN GIVE ALTERNATIVE NAME IN THREE WAYS:
-- 		->ANNUAL_SALARY
--      ->ANNUALSALARY
--      ->"ANNUALSALARY"
-- WAQTD ANNUAL SALARY OF THE EMP WITHIN THE TABLE
SELECT SAL*12 AS ANNUALSALARY
FROM EMP;

SELECT SAL*12 AS ANNUAL_SALARY
FROM EMP;

SELECT SAL*12 AS "ANNUAL SALARY"
FROM EMP;
        