-- MONTHS BETWEEN():
--    THIS FUNCTION IS USED TO GIVE THE NUMBER OF MONTHS BETWEEN FROM TWO DIFFERENT VALUES
-- SYNTAX:
--   MONTHS_BETWEEN(VALUE1,VALUE2)
  
  SELECT MONTHS_BETWEEN('2026-02-14','2026-04-14')
  FROM DUAL;

-- ADD MONTHS():
--    THIS FUNCTION IS USED TO ADD(OR) SUBSTRACT NUMBER OF MONTHS FROM A GIVEN DATE
--    SYNTAX:
--    ADD_MONTHS(DATE,NO.OFMONTHS)

SELECT ADD_MONTHS('2026-04-14',4)
FROM DUAL;

-- LAST_DAY():
--   THIS FUNCTION IS USED TO FIND THE ENDING OF THE MONTH
--   
--   SYNTAX:
--   LAST_DAY(DATE)
  
  SELECT LAST_DAY('2026-04-14')
  FROM DUAL;
--   
--   NVL():
--     THIS FUNCTION IS USED TO REPLACE THE NULL VALUES WITH USER GIVEN VALUES
--     
--     SYNTAX:
--     NVL(ARG1,ARG2)
    
    SELECT COMM , NVL(COMM,100)
    FROM employee.EMP;
  
--   WAQTD TOTAL EARNINGS OF EMPLOYEES(SAL+COMM)

  SELECT SAL + NVL(COMM+0)
  FROM employee.EMP;
  
--   TO_CHAR():
--     THIS FUNCTION IS USED TO CONVERT DATE INTO FORMAT MODELS
--     
--     SYNTAX:
--      TO_CHAR(DATE,'FORMAT_MODELS')
     
     SELECT TO_CHAR(SYSTIMESTAMP,'DAY')
     FROM DUAL;
     
     
--      TO_DATE():
--        IT IS USED TO CONVERT THE GIVEN VALUES INTO DATE VALUES
--        EX:
        SELECT TO_CHAR(TO_DATE('2026-04-14'),'DAY')
        FROM DUAL;
        
-- WAQTD DETAILS OF EMPLOYEES WHO ARE HIRED IN FEB

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE,'MON')='FEB';

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE,'MM')=2;

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE,'MONTH')='FEBRUARY ';
        
        

