-- DISTINCT:
-- 	DISTINCT IS A KEYWORD OR CLAUSE WHICH IS USED TO REMOVE REPEATED or DUPLICATE VALUES FROM RESULT TABLE
--     DISTINCT MUST BE A FIRST ARGUMENT IN SELECT CLAUSE BEFORE ALL THE CALUMN NAMES.
--     THIS WILL MAKE CHANGES IN RESULT TABLE ONLY
--     ALONG WITH DISTINCT WE CAN USE MULTIPLE COL NAMES

USE EMPLOYEE;
SELECT distinct DEPTNO
FROM EMP;

-- --------------------------------------

SELECT distinct JOB,DEPTNO
FROM EMP;

    