-- SELECTION:
--     IT IS THE PROCESS OF RETRIVING DATA FROM THE TABLES BY SELECTING BOTH ROWS AS WELL AS COLUMNS
--     SYNTEX:
--     SELECT*/COL_NAME/EXP/[DISTINCT]/[ALLIAS]
--     FROM TABLE_NAME
--     WHERE <FILTER_CONDITONS>;

-- WAQTD NAME AND SALARY OD AN EMPLOYEES WHO ARE EARNING MORE THAN 1500
USE EMPLOYEE;
SELECT ENAME,SAL
FROM EMP
WHERE SAL > 1500;

-- WAQTD DETAILS OF AN EMPLOYEES WHO ARE EARNING MORE THAN 4000
SELECT *
FROM EMP
WHERE SAL < 4000;

--  WAQTD NAME AND HIREDATE OF AN EMPLOYEE WHO ARE HIRED AFTER 14-FEB-1982 
SELECT ENAME,HIREDATE
FROM emp
WHERE HIREDATE > '1982-02-14';

-- WAQTD DETAILS OF ALL THE EMPLOYEES EXCEPT MANAGER
SELECT *
FROM EMP
WHERE JOB != 'MANAGER';
