-- LOGICAL OPERATORS:
-- IT IS USED TO WRITE THE MULTIPLE CONDITION IN WHERE CLAUSE.
-- THE LOGICAL OPERATORS IS DIVIDED IN THREE TYPES. THEY ARE:
--     -> AND
--     -> OR
--     -> NOT

-- AND:
--     IT IS A BINARY OPERATOR WHICH ACCEPTS TWO CONDITIONS AS OPERENTS. IT WILL GIVE TRUE WHEN BOTH THE CONDITIONS
--     IS SATISFIED.
    
   --  WAQTD DETAILS OF THE EMPLOYEES WORKING AS A CLERK AND EARNING LESS THAN 1500.
   USE EMPLOYEE;
   SELECT *
   FROM emp
   WHERE JOB = 'CLERK' AND SAL < 1500;
   
   -- WAQTD NAME AND HIREDATE OF AN EMPLOYEES WORKING AS A MANAGER IN DEPT 30.
   
   SELECT ENAME, HIREDATE
   FROM emp
   WHERE JOB = 'MANAGER' AND DEPTNO = 30;
    
-- 3.WAQTD DETAIL S OF THe EMP ALoNG WITh AnNUAL SALAry fF THEY ARE
-- WORKING IN DEPT 30 AS SALESMAN AND THEIR ANNUAL SALARy HAS TO BE
-- GREATER THAN 14000.

SELECT EMP. *, SAL*12
FROM emp
WHERE (DEPTNO = 30 AND (JOB = 'SALESMAN' AND SAL*12 > 14000));
-- 4.WAQTD ALL THE DETAILS OF THE EMP WORKING IN DEPT 30 OR AS
-- ANALYST

SELECT *
FROM emp
WHERE JOB = 'ANALYST' OR DEPTNO = 30;
-- 5.WAQTD NAMES OF THE EMPMLOYEES WHOS SALARY IS LESS THAN 1100
-- AND THEIR DESIGNATION IS CLERK

SELECT ENAME 
FROM emp
WHERE SAL < 1100 AND JOB = 'CLERK';
-- 6.WAQTD NAME_ SAL ANNUAL SAL AND DEPTNO IF DEPTNO IS 20 EARNING
-- SAL MORE THAN 1100 AND ANNUAL SALARY EXCEEDS 12000
SELECT ENAME, SAL, SAL*12 AS ANNUALSALARY, DEPTNO
FROM EMP
WHERE DEPTNO = 20 AND SAL > 1100 AND SAL*12 > 12000;
-- 7.WAOTD EMPNO AND NAMES OF THE EMPLOYEES WORKING AS MANAGER IN
-- DEPT 20
SELECT EMPNO,ENAME
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO = 20;
-- 8.WAQTD DETAILS OF EMPLOYEES WORKING IN DEPT 20 OR 30
SELECT *
FROM emp
WHERE DEPTNO IN(20,30);
-- 9.WAQTD DETAILS OF EMPLO YEES WORKING AS ANAL YST IN DEPT 10.
SELECT *
FROM emp
WHERE JOB = 'ANALYST' AND DEPTNO = 10;
-- 10.WAQTD DETAILS OF EMPLOYEE WORKING AS PRESIDENT WITH SALARY OF
-- RUPEES 4000
SELECT *
FROM EMP
WHERE JOB = 'PRESIDENT' AND SAL = 4000;
-- 11.WAQTD NAMES AND DEPTNO JOB OF EMPS WOEKING AS CLERK IN DEPT
-- 10 OR 20
SELECT ENAME,DEPTNO,JOB
FROM emp
WHERE JOB = 'CLERK' AND DEPTNO IN (10,20);
-- 12.WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK OR MANAGER IN
-- DEPT 10
SELECT *
FROM EMP
WHERE JOB IN('CLERK','MANAGER') AND DEPTNO = 10;
-- 13.WAOTD NAMES OF EMPLOYEES WORKING IN DEPT 10 20. 30. 40.
SELECT ENAME
FROM emp
WHERE DEPTNO IN (10,20,30,40);
-- 14.WAQTD DETAILS OF EMPLOYEES WITH EMPNO 7902,7839.
SELECT *
FROM emp
WHERE EMPNO IN(7902,7839);
-- 15 WAQTD DETAILS OF EMPLOYEES WORKING AS MANAGER OR SALESMAN
-- OR CLERK
SELECT *
FROM emp
WHERE JOB IN ('MANAGER','SALESMAN','CLERK');
-- 16.WAOTD NAMES OF EMPLOYEES HIRED AFTER 81 AND BEFORE 87
SELECT ENAME
FROM EMP
WHERE HIREDATE < '1981-01-01' AND HIREDATE < '1987-12-31';
-- 17.WAOTD DETAILS OF EMPLOYEeS EARNING MORE THAN 1250 BUT LESS
-- THAN 3000
SELECT *
FROM EMP
WHERE SAL > 1250 AND SAL < 3000;
-- 18.WAOTD NAMES OF EMPLOYEES HIRED AFTER 81 INTO DEPT 10 OR 30
SELECT ENAME
FROM EMP
WHERE HIREDATE >'1981-01-01' AND DEPTNO IN(10,30);
-- 19 WAOTD NAMES OF EMPLOYEES ALONG WITH ANNUAL SALARY FOR THE
-- EMPLOYEES WORKING AS MANAGER OR CLERK IN DEPT 10 OR 30
SELECT ENAME,SAL*12 ANNUALSALARY
FROM EMP
WHERE JOB IN ('MANAGER','CLERK') AND DEPTNO IN(10,30);

-- 20.WAOTD ALL THE DETAILS ALONG WITH ANNUAL SALARY IF SAL IS
-- BETWEEN 1000 AND 4000 ANNUAL SALARY MORE THAN 15000

SELECT EMP.* , SAL* 12 ANNUAL_SALARY
FROM EMP
WHERE (SAL>= 1000 AND (SAL <=4000) AND (SAL*12 > 15000));