-- special operators:
-- the special operator is mainly as(IN,NOT IN,BETWEEN,NOT BETWEEN,IS , IS NOT,LIKE,NOT LIKE)
-- IN operator:
--  THIS OPERATOR IS USED TO COMPARE WITH MULTIPLE VALUES AT A TIME.
--  SYNTEX:COL_NAME/EXP IN(VAL1,VAL2,VAL3....)

-- WAQTD DETAILS OF EMPLOYEES WORKING MANAGER OR CLERK
USE EMPLOYEE;
SELECT *
FROM EMP
WHERE JOB IN ('MANAGER','CLERK');

-- WAQTD DETAILS OF EMPLOYEES WORKING IN DEPT 10,20,30,40
SELECT *
FROM EMP
WHERE DEPTNO IN(10,20,30,40);

-- WAQTD DETAILS OF EMPLOYEES WORKING IN DEPT 10 OR 30 AS MANAGER OR CLERK
SELECT *
FROM EMP
WHERE JOB IN ('MANAGER','CLERK') AND DEPTNO IN(10,30);